apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.29.0
        name: audiobookshelf
        ports:
        - containerPort: 3005
          protocol: TCP
        volumeMounts:
          - name: abs-audiobooks
            mountPath: /audiobooks
          - name: abs-podcasts
            mountPath: /podcasts
          - name: abs-config
            mountPath: /config
          - name: abs-metadata
            mountPath: /metadata
        envFrom:
          - configMapRef:
              name: audiobookshelf-configmap
      volumes:
        - name: abs-audiobooks
          persistentVolumeClaim:
            claimName: abs-audiobooks-pvc
        - name: abs-podcasts
          persistentVolumeClaim:
            claimName: abs-podcasts-pvc
        - name: abs-config
          persistentVolumeClaim:
            claimName: abs-config-pvc
        - name: abs-metadata
          persistentVolumeClaim:
            claimName: abs-metadata-pvc
      restartPolicy: Always
